[[section-solution-strategy]]


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
== Solution Strategy
Una de las piedras angulares sobre la que esta basada la aplicación es el almacenamiento descentralizado de la información del usuario. SOLID no permite llevar a cabo esta administración de datos así que la estructura del proyecto girará entorno a el.

Para desarrollar este proyecto hemos decidio usar React Native que, además de funcionar perfectamente con SOLID, permite desplegar la aplicación facilmente tanto en Android como en iOS. 


=== Decisiones tecnológicas
==== Librerías
Las principales librerías a usar son las siguientes:

* React: Biblioteca de Javascript usada para crear el front-end de la aplicación.
* Node.js: Se usa para crear la parte del servidor de la aplicación.
* SOLID: Es usado a modo de base de datos descentralizada, aprovechando su fácil integración con react gracias a la librería Solid React Components.
* Leafleat: Se usan los componentes que nos proporciona React-leafleat para implementar los mapas los mapas de la aplicación.

==== Estructura
Para conseguir que el proyecto sea mantenibile su estructura estará basada en contenedores, que serán implementados usando la herramienta Docker. 

==== Otras decisiones 
Hemos decidido usar Github para el control de versiones. Github tambien permite poder llevar un registro del trabajo realizado por los participantes mediante los pull request.

