[[section-solution-strategy]]

== Solution Strategy
Una de las piedras angulares sobre la que esta basada la aplicación es el almacenamiento descentralizado de la información del usuario. SOLID nos permite llevar a cabo esta administración de datos así que la estructura del proyecto girará entorno a el.

Para desarrollar este proyecto hemos decidio usar React Native que, además de funcionar perfectamente con SOLID, permite desplegar la aplicación facilmente tanto en Android como en iOS. 


=== Decisiones tecnológicas
==== Librerías
Las principales librerías a usar son las siguientes:

* React: Biblioteca de Javascript usada para crear el front-end de la aplicación.
* Node.js: Se usa para crear la parte del servidor de la aplicación.
* SOLID: Es usado a modo de base de datos descentralizada, aprovechando su fácil integración con react gracias a la librería Solid React Components.
* Leafleat: Se usan los componentes que nos proporciona React-leafleat para implementar los mapas los mapas de la aplicación.

==== Estructura
Para conseguir que el proyecto sea mantenibile su estructura estará basada en contenedores, que serán implementados usando la herramienta Docker. 

==== Otras decisiones 
Hemos decidido usar Github para el control de versiones. Github tambien permite poder llevar un registro del trabajo realizado por los participantes mediante los pull request.

