[[section-runtime-view]]
== Vista en tiempo de ejecución


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Log In>

Al iniciar la aplicación el usuario debe iniciar sesión con SOLID para acceder a la aplicación.

.El proceso de logueo seguiría los siguientes pasos:
. El usuario entra en la aplicación y solicita loguearse
. Se le pasa un formulario para rellenar los credentials
. El usuario rellena el formulario con sus credenciales
. Se realiza una autenticación de la información aportada
. Se responde autorizando o denegando el acceso dependiendo del resultado de la autenticación


[plantuml,"Sequence diagram",png]
----
actor Usuario
participant Radarin
database Pod as "Pod del usuario"
Usuario -> Radarin: Petición de autenticación
Radarin --> Pod: Validación de credenciales
Radarin  <- Pod: Respuesta a la validación
Usuario <- Radarin: Respuesta a la autenticación
----

